### ISSUE TITLE
Cell ID mismatch in polygon list

### ISSUE THREAD

**Issue by mruffalo** [hubmapconsortium/sprm#11]
Fewer cells are listed in `cell_polygons_spatial.csv` than in other output files. This causes a failure in @ilan-gold's conversion to UI data structures.

**Comment by ilan-gold** [comment]
There are actually more ids in the `cell_centers.csv` file which Ted suggested might be another alternate source of ground truth.  This isn't my show, but I really think (part of) the solution here needs to be checking all the files that are output both against each other and against the mask to make sure ids match both in quality and quantity.

<img width="903" alt="Screen Shot 2021-06-21 at 2 36 01 PM" src="https://user-images.githubusercontent.com/43999641/122811365-62d93580-d29e-11eb-96b0-7d953d3a24a4.png">
<img width="971" alt="Screen Shot 2021-06-21 at 12 09 16 PM" src="https://user-images.githubusercontent.com/43999641/122811366-6371cc00-d29e-11eb-996f-ccb9f4add788.png">

**Comment by TeddyZ95** [comment]
For the cell center we are actually getting all the cell centers in the mask. This is how the algorithm works and to change this would require some heavy rewriting of the code base or changing of the mask when processing to get the filter list of cells that SPRM processes. I've made the necessary changes to validate that the features files other than the `cell_center.csv` have the same cell ids.

**Comment by ilan-gold** [comment]
@TeddyZ95 Who is the `cell_center.csv` file for?  Is there a reason to not just discard it?

**Comment by TeddyZ95** [comment]
@ilan-gold This is used to calculate a cell adjacency matrix.

**Comment by ilan-gold** [comment]
Does the cell adjacency matrix include the extra cells?  Wouldn't that make it also incommensurable with the rest of SPRM where the number of cells is fewer?

**Comment by TeddyZ95** [comment]
Not necessary since the index of the cell should be identical. As in cell id 11000 should be the same in the cell adj matrix. All that is telling you is what cells are neighboring other cells. Since the issue with skipping cell ID or duplicate cell IDs have been fixed. But I do agree that they should match, but it would require some rewriting in our algorithm. But since you guys don't use the cell_centers I think it's fine to leave as is.

**Comment by ilan-gold** [comment]
Ok that makes sense.  My only concern was that if it was "add an edge between the k-nearest neighbors of the query cell" rather than "all cells within this radius are given an edge to this query cell," then the results would be somewhat off.  Doesn't sound like that's the case though!

**Comment by mruffalo** [comment]
As per @TeddyZ95, fixed in https://github.com/hubmapconsortium/sprm/commit/b4b142dc1e9aad91e549ebf94ee1e6c02d2f9e35.
